spring:
  datasource:
    url: jdbc:postgresql://dpg-d0tds5re5dus73fpf74g-a:5432/animal_clinicdb
    username: animal_clinicdb_user
    password: KTMcsQG6uPweiNF1dxSMu7fuSLKprrf7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: hs6823uhgfe98u3yec8ybefy784589fhn
  expiration-time: 3600000
