spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animal_clinicDB
    username: postgres
    password: max228488
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: hs6823uhgfe98u3yec8ybefy784589fhn
  expiration-time: 3600000
