spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animal_clinicDB
    username: postgres
    password: max228488
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update